### ISSUE TITLE
AT_B_1

### ISSUE THREAD

**Issue by Ozia112** [Ozia112/Team-2-FSE-repo#168]
# (B)Product files missing
The following files were mistakenly deleted and need to be **restored**:
- [Definition of users-clients1.1.md](https://github.com/Ozia112/Team-2-FSE-repo/blob/FIS-Project-Stage-1/B_task/Definition%20%20of%20users-clients1.1.md)
- [Product.md](https://github.com/Ozia112/Team-2-FSE-repo/blob/FIS-Project-Stage-1/B_task/Product.md)
- [Value proposition1.0.md](https://github.com/Ozia112/Team-2-FSE-repo/blob/FIS-Project-Stage-1/B_task/Value%20proposition1.0.md)

>Assignated to: @ALEXANDER242164

**Comment by ALEXANDER242164** [comment]
Ya se terminó
